#for server.r
install.packages("shiny")
install.packages("plyr")
install.packages("dplyr")
install.packages("ggthemes")
install.packages("graphics")
install.packages("tidyverse")
install.packages("DT")
install.packages("RcppArmadillo")
install.packages("ggplot2")
install.packages("lda")
install.packages("corpus")
install.packages("qdap")
install.packages("qdapRegex")
install.packages("quanteda")
install.packages("reshape2")
install.packages("RTextTools")
install.packages("RColorBrewer")
install.packages("tibble")
install.packages("mallet")
install.packages("stm")
install.packages("stringi")
install.packages("devtools")
install.packages("htmlwidgets")
install.packages("streamgraph")
install.packages("stringr")
install.packages("tidyr")
install.packages("tidytext")
install.packages("tm")
install.packages("topicmodels")
install.packages("wordcloud")
install.packages("wordcloud2")
install.packages("rJava")

#for extracting cache files
install.packages("readr")
